#!/bin/sh

#echo "Extract BB"
extractbb -m *.jpg *.png *.pdf

echo "BUILD 1"
latex Book.tex
makeindex Book
echo "Intro Bib"
bibtex Introduction
echo "Hall Bib"
bibtex Hall
echo "Halsmer Bib"
bibtex Halsmer
echo "Ewert Bib"
bibtex Ewert
echo "Sich Bib"
bibtex Sich
echo "Holloway Bib"
bibtex Holloway
echo "Bartlett1 Bib"
bibtex Bartlett1
echo "Bartlett2 Bib"
bibtex Bartlett2
echo "Mignea Bib"
bibtex Mignea2
echo "BUILD 2"
latex Book.tex
makeindex Book
echo "BUILD 3"
latex Book.tex
makeindex Book
latex Book.tex
latex Book.tex
latex Book.tex
