#!/bin/sh

echo "BUILD 1"
pdflatex Book.tex
makeindex Book
echo "Hall Bib"
bibtex Hall
echo "Halsmer Bib"
bibtex Halsmer
echo "Ewert Bib"
bibtex Ewert
echo "Sich Bib"
bibtex Sich
echo "Holloway Bib"
bibtex Holloway
echo "Bartlett1 Bib"
bibtex Bartlett1
echo "Bartlett2 Bib"
bibtex Bartlett2
echo "Mignea3 Bib"
bibtex Mignea3
echo "BUILD 2"
pdflatex Book.tex
makeindex Book
echo "BUILD 3"
pdflatex Book.tex
makeindex Book
